### ISSUE TITLE
openssl version

### ISSUE THREAD

**Issue by gonmf** [sora-chan/wakaba#2]
I can't seem to be able to compile it.

What version of OpenSSL did you use? Any package other than *libssl-dev*?

Thank you

**Comment by sora-chan** [comment]
The default openssl that comes with Arch Linux.
Post errors.

**Comment by gonmf** [comment]
The symbol *SSL_COMP_free_compression_methods* is undefined, it was added on 1.0.2 and I have 1.0.1 apparently. Oh well.

**Comment by sora-chan** [comment]
Time to update.
>Using Debian.

**Comment by gonmf** [comment]
Heh
